# Generated by Django 4.2.5 on 2023-09-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='population',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
