# Generated by Django 4.2.5 on 2023-09-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albania', '0002_alter_city_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
